VelvetVogue/Models/ErrorViewModel.cs
namespace VelvetVogue.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VelvetVogue/Models/ViewModels/AddNewItemsViewModel.cs
namespace VelvetVogue.Models.ViewModels
{
    public class AddNewItemsViewModel
    {

    }
}

VelvetVogue/Models/ViewModels/AddNewLoginViewModel.cs
namespace VelvetVogue.Models.ViewModels
{
    public class AddNewLoginViewModel
    {

    }
}

VelvetVogue/Models/ViewModels/CheckingCurrentLoginViewModel.cs
namespace VelvetVogue.Models.ViewModels
{
    public class CheckingCurrentLoginViewModel
    {
        public string Success_message { get; set; } = string.Empty;

        public string Error_message { get; set; } = string.Empty;
    }
}

VelvetVogue/Models/ViewModels/ContactUSViewModel.cs
namespace VelvetVogue.Models.ViewModels
{
    public class ContactUSViewModel
    {

    }
}

VelvetVogue/Models/ViewModels/ErrorViewModel.cs
namespace VelvetVogue.Models.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VelvetVogue/Models/ViewModels/InquiriesViewModel.cs
namespace VelvetVogue.Models.ViewModels
{
    public class InquiriesViewModel
    {

    }
}

VelvetVogue/Models/ViewModels/MainLoginViewModel.cs
namespace VelvetVogue.Models.ViewModels
{
    public class MainLoginViewModel
    {

    }
}

VelvetVogue/Models/ViewModels/NewLoginDetailsViewModel.cs
namespace VelvetVogue.Models.ViewModels
{
    public class NewLoginDetailsViewModel
    {

    }
}

VelvetVogue/Controllers/AddNewItemsController.cs
using Microsoft.AspNetCore.Mvc;
using VelvetVogue.Models.ViewModels;

namespace VelvetVogue.Controllers
{
    public class AddNewItemsController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new AddNewItemsViewModel());
        }
    }
}

VelvetVogue/Controllers/AddNewLoginController.cs
using Microsoft.AspNetCore.Mvc;
using VelvetVogue.Models.ViewModels;

namespace VelvetVogue.Controllers
{
    public class AddNewLoginController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new AddNewLoginViewModel());
        }
    }
}

VelvetVogue/Controllers/CheckingCurrentLoginController.cs
using Microsoft.AspNetCore.Mvc;
using VelvetVogue.Models.ViewModels;

namespace VelvetVogue.Controllers
{
    public class CheckingCurrentLoginController : Controller
    {
        [HttpPost]
        public IActionResult Index(CheckingCurrentLoginViewModel Model)
        {
            return View();
        }
    }
}

VelvetVogue/Controllers/ContactUSController.cs
using Microsoft.AspNetCore.Mvc;
using VelvetVogue.Models.ViewModels;

namespace VelvetVogue.Controllers
{
    public class ContactUSController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new ContactUSViewModel());
        }

        [HttpPost]
        public IActionResult Index(ContactUSViewModel Model)
        {
            return View();
        }
    }
}

VelvetVogue/Controllers/GentsItemsController.cs
using Microsoft.AspNetCore.Mvc;

namespace VelvetVogue.Controllers
{
    public class GentsItemsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

VelvetVogue/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using VelvetVogue.Models.ViewModels;

namespace VelvetVogue.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AboutUS()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VelvetVogue/Controllers/InquiriesController.cs
using Microsoft.AspNetCore.Mvc;
using VelvetVogue.Models.ViewModels;

namespace VelvetVogue.Controllers
{
    public class InquiriesController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new InquiriesViewModel());
        }
    }
}

VelvetVogue/Controllers/MainLoginController.cs
using Microsoft.AspNetCore.Mvc;
using VelvetVogue.Models.ViewModels;

namespace VelvetVogue.Controllers
{
    public class MainLoginController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new MainLoginViewModel());
        }
    }
}

VelvetVogue/Controllers/UpdatingLoginDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using VelvetVogue.Models.ViewModels;

namespace VelvetVogue.Controllers
{
    public class UpdatingLoginDetailsController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new NewLoginDetailsViewModel());
        }
    }
}

VelvetVogue/Views/AddNewLogin/Index.cshtml
@{
     @model VelvetVogue.Models.ViewModels.AddNewLoginViewModel 
}

<div class="container">

    <!--row 01 -->
    <div class="CardAlignment">

        <!--Border-->
        <div class="Customborder">

            <!--icon-->
            <div class="row" style="padding-top:3%">
                <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12 d-flex justify-content-center">
                    <div>
                       <img src="~/img/Login.png" /><br />
                        
                    </div>

                   
                </div>
            </div>

            <!--icon label-->
            <div class="row" style="padding-top:1%">
                <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12 d-flex justify-content-center">
                    <div>
                        
                        <label style="color:slategray">Velvet Vogue</label>
                    </div>


                </div>
            </div>

            <!--Username-->
            <div class="row" style="padding-top:5%">
                <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                   @*  <div>
                        <label class="fonts labelAligment"> Username</label>
                         
                    </div> *@

                    <div class="TextBoxAligment">
                        <input type="text" placeholder="Username" class="form-control TextboxesSize TextBoxBorderStyle" />
                    </div>
                </div>
            </div>

            <!--Password-->
            <div class="row" style="padding-top:5%">
                <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                    @* <div>
                        <label class="fonts labelAligment">Password</label>

                    </div> *@

                    <div class="TextBoxAligment">
                        <input type="password" placeholder="Password" class="form-control TextboxesSize TextBoxBorderStyle" />
                    </div>
                </div>
            </div>

            <!--Confirm Password-->
            <div class="row" style="padding-top:5%">
                <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                   @*  <div>
                        <label class="fonts labelAligment">Confirm Password</label>

                    </div> *@

                    <div class="TextBoxAligment">
                        <input type="password" placeholder="Confirm Password" class="form-control TextboxesSize TextBoxBorderStyle" />
                    </div>
                </div>
            </div>

            <!--hr-->
            <div class="row" style="padding-top:5%">
                <div class="col-12 col-md-12 col-xl-12 col-lg-12 col-xxl-12">
                    <hr />
                </div>
            </div>

            <!--btnSave-->
            <div class="row" style="padding-bottom:3%">
                <div class="col-12 col-md-12 col-xl-12 col-lg-12 col-xxl-12">
                    <div style="display:flex;justify-content:center">
                        <button type="submit" class="btn btn-primary btnSave">Save</button>
                    </div>
                   
                </div>
            </div>

        </div>

    </div>

    <!--Use for fix bug (box shadow not showing issue)-->
    <div class="row" style="margin-top:5%">
    </div>
</div>

VelvetVogue/Views/CheckingCurrentLogin/Index.cshtml
@{
    @model VelvetVogue.Models.ViewModels.CheckingCurrentLoginViewModel
}

<div class="container">

    <!--Success message-->
    <div class="row" style="margin-top:3%">
        <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
            <label style="font-size:110%;font-weight:bold;color:green">Success Message</label>
        </div>
    </div>

    <!--Error message-->
    <div class="row" style="margin-top:3%">
        <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
            <label style="font-size:110%;font-weight:bold">Error Message</label>
        </div>
    </div>

    <!--btnAddNewPassword-->
    <div class="row">
        <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
            <a class="btn btn-primary" asp-controller="UpdatingLoginDetails" asp-action="Index">Add New Login</a>
        </div>
    </div>

</div>

VelvetVogue/Views/GentsItems/Index.cshtml
@{

}

<div class="container">

    <div class="row">

        <div class="col-12 col-md-3 col-xl-3 col-lg-3 col-xxl-3" style="margin-top:2%">

            <div class="card" style="width: 18rem;">

                <img src="~/img/01.jpg" class="card-img-top" alt="Empty">

                <div class="card-body">

                    <h5 class="card-title">Title</h5>

                    <p class="card-text">Rs.1500</p>

                    <a href="#" class="btn btn-primary" style="background-color:black;border-color:black">See More Details</a>
                </div>

            </div>
        </div>

    </div>

</div>

VelvetVogue/Views/Home/AboutUS.cshtml
@{
    ViewData["Title"] = "Privacy Policy";
}

<div class="container">

    <div class="row mt-auto">

        <!--Left side-->
        <div class="col-12 col-md-6">

            <div class="row">

                <div class="col-12 col-md-12">
                    <h2 class="fw-bold clsAboutUs">ABOUT US</h2>
                </div>
            </div>

            <div class="row">

                <div class="col-12 col-md-12">
                    <p class="paragraph" style="">
                        Welcome to Velvet Vogue – where fashion meets elegance. We are a modern clothing brand
                        committed to delivering high-quality, stylish, and comfortable apparel for men, women,
                        and kids. Whether you're looking for everyday basics or standout pieces, our collections
                        are designed to make you look and feel your best. At Velvet Vogue, we blend timeless trends
                        with fresh designs, ensuring every item reflects sophistication and comfort. Join us in
                        celebrating individuality and effortless style.
                    </p>
                </div>
            </div>

        </div>

        <!--right side-->
        <div class="col-6 col-md-6 ">
            <img src="/img/ABDimg02.jpg" class="img" />

        </div>

    </div>

</div>

VelvetVogue/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<!--Banner Img-->
<div class="container-fluid p-0 m-0">

    <div id="carouselBanner" class="carousel slide">

        <div class="carousel-indicators">

            <button type="button" data-bs-target="#carouselBanner" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselBanner" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselBanner" data-bs-slide-to="2" aria-label="Slide 3"></button>

        </div>

        <div class="carousel-inner">

            <div class="carousel-item active">
                <img src="~/img/MainBanner.png" class="d-block w-100 img-fluid" style="height:700px;object-fit:cover;" alt="No Image">
            </div>

            <div class="carousel-item">
                <img src="~/img/MainBanner.png" class="d-block w-100 img-fluid" style="height:700px;object-fit:cover;" alt="No Image">
            </div>

            <div class="carousel-item">
                <img src="~/img/MainBanner.png" class="d-block w-100 img-fluid" style="height:700px;object-fit:cover;" alt="No Image">
            </div>

        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#carouselBanner" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>

        <button class="carousel-control-next" type="button" data-bs-target="#carouselBanner" data-bs-slide="next">

            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>

        </button>

    </div>
</div>


<div class="container" style="margin-top:5%">

    <!--Categories row-->
    <div class="row">
        <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">

            <div class="text-center">
                <label style="font-size:150%" class="fw-bold CategoryText">CATEGORIES</label>
            </div>

        </div>
    </div>

    <!--Category Cards-->
    <div class="row">

        <div class="col-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4 d-flex justify-content-center" style="padding-top:3%">

            <div class="card Mycard" style="">
                <img src="/img/mens.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Gents Items</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card’s content.</p>
                    <a class="btn btn-primary" asp-controller="GentsItems" asp-action="Index">Gents</a>
                </div>
            </div>

        </div>

        <div class="col-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4 d-flex justify-content-center" style="padding-top:3%">

            <div class="card d-flex Mycard" style="">
                <img src="/img/Ladies.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Ladies Items</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card’s content.</p>
                    <a asp-action="" class="btn btn-primary">Ladies</a>
                </div>
            </div>

        </div>

        <div class="col-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4 d-flex justify-content-center" style="padding-top:3%">

            <div class="card d-flex Mycard" style="">
                <img src="/img/kids.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Kids Items</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card’s content.</p>
                    <a asp-action="" class="btn btn-primary">Kids</a>
                </div>
            </div>

        </div>


    </div>

    <!--new arrivals-->
    <div class="row" style="margin-top:5%">
        <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">

            <div class="text-center">
                <label style="font-size:150%" class="fw-bold CategoryText">NEW ARRIVALS</label>
            </div>

        </div>
    </div>

   
</div>

<!--Carousel-->
<div class="container-fluid" style="padding-left:0;padding-right:0;padding-bottom:6%;padding-top:3%">
    <!--New Cards-->
    <div id="carouselExampleIndicators" class="carousel slide">

        <div class="carousel-indicators">

            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>

        </div>

        <div class="carousel-inner">

            <div class="carousel-item active">
                <img src="~/img/01.jpg" class="d-block w-100 img-fluid" style="height:600px;object-fit:cover;" alt="...">
            </div>

            <div class="carousel-item">
                <img src="~/img/02.jpg" class="d-block w-100 img-fluid" style="height:500px;object-fit:cover;" alt="...">
            </div>

            <div class="carousel-item">
                <img src="~/img/03.jpg" class="d-block w-100 img-fluid" style="height:500px;object-fit:cover;" alt="...">
            </div>

        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>

        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">

            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>

        </button>

    </div>

</div>


<!--Brands-->
<div class="row">
    <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">

        <div class="text-center">
            <label style="font-size:150%" class="fw-bold CategoryText">BRANDS</label>
        </div>

    </div>
</div>

<!--Brand names-->
<div class="container" style="margin-bottom:10%">

    <div class="row">

        <div class="col-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4" style="margin-top:5%">
            <img src="~/img/Nike.jpg" class="brandsSize" style="object-fit:cover" />
        </div>

        <div class="col-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4" style="margin-top:5%">
            <img src="~/img/Gucci.jpg" class="brandsSize" style="object-fit:cover" />
        </div>

        <div class="col-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4" style="margin-top:5%">
            <img src="~/img/Adidas.jpg" class="brandsSize" style="object-fit:cover" />
        </div>

    </div>
</div>

VelvetVogue/Views/MainLogin/Index.cshtml
@{
    @model VelvetVogue.Models.ViewModels.MainLoginViewModel
}

<div class="container">

    <!--row 01 -->
    <div class="CardAlignment">

        <!--Border-->
        <div class="Customborder">

            <!--icon-->
            <div style="padding-top:3%">
                <div class=" d-flex justify-content-center">
                    <div>
                        <img src="~/img/Login.png" /><br />

                    </div>


                </div>
            </div>

            <!--icon label-->
            <div  style="padding-top:1%">
                <div class=" d-flex justify-content-center">
                    <div>

                        <label style="color:slategray">LOGIN</label>
                    </div>


                </div>
            </div>

            <!--Username-->
            <div  style="padding-top:7%">
                <div >
                    @*  <div>
                        <label class="fonts labelAligment"> Username</label>
                         
                    </div> *@

                    <div class="TextBoxAligment">
                        <input type="text" placeholder="Username" class="form-control TextboxesSize TextBoxBorderStyle" />
                    </div>
                </div>
            </div>

            <!--Password-->
            <div style="padding-top:9%">
                <div >
                    @* <div>
                        <label class="fonts labelAligment">Password</label>

                    </div> *@

                    <div class="TextBoxAligment">
                        <input type="password" placeholder="Password" class="form-control TextboxesSize TextBoxBorderStyle" />
                    </div>
                </div>
            </div>

            <!--Remember my login-->
            <div  style="padding-top:2%">
                <div>
                   
                    <div class="TextBoxAligment">
                        <input type="checkbox" />
                        <label style="color:slategray">Remember my login details</label>
                    </div>
                </div>
            </div>

            <!--hr-->
            <div style="padding-top:5%">
                <div>
                    <hr />
                </div>
            </div>

            <!--btnSave-->
            <div style="padding-bottom:3%">
                <div>
                    <div style="display:flex;justify-content:center">
                        <button type="submit" class="btn btn-primary btnSave">LOGIN</button>
                    </div>

                </div>
            </div>

            <!--I dont have a login-->
            <div style="padding-bottom:3%">
                <div>

                    <div style="display:flex;justify-content:center">
                        <a asp-controller="AddNewLogin" class="text-decoration-none" style="color:gray">I dont have a login</a>
                    </div>

                </div>
            </div>

        </div>

    </div>

    <!--Use for fix bug (box shadow not showing issue)-->
    <div class="row" style="margin-top:5%">

    </div>
</div>

VelvetVogue/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VelvetVogue</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VelvetVogue.styles.css" asp-append-version="true" />
</head>
<body>

    <header class="Mysticky">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom  mb-3">

            <div class="container">

                <!--brand name-->
                <a class="navbar-brand fw-bold" style="font-size:130%" asp-area="" asp-controller="Home" asp-action="Index">Velvet Vogue</a>

                <!--Hamburger btn-->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#MainNav" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!--My code-->
                <div class="navbar-collapse collapse " id="MainNav">

                    <ul class="navbar-nav ms-auto gap-3">

                        <li class="nav-item NavBarTextAlignment">
                            <a class="text-decoration-none  NavBarText" asp-area="" asp-controller="Inquiries" asp-action="Index">INQUIRIES</a>
                        </li>

                        <li class="nav-item NavBarTextAlignment">
                            <a class="text-decoration-none  NavBarText" asp-area="" asp-controller="Home" asp-action="AboutUS">ABOUT US</a>
                        </li>

                        <li class="nav-item NavBarTextAlignment">
                            <a class="text-decoration-none NavBarText NavBarTextAlignment" asp-area="" asp-controller="ContactUS" asp-action="">CONTACT US</a>
                        </li>

                       
                        <!--Admin || dropdown-->
                        <li class="nav-item dropdown NavBarTextAlignment" style="">
                           
                           
                            <a class="dropdown-toggle text-decoration-none NavBarText" style="color:black;" data-bs-toggle="dropdown">ADMIN</a>

                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" style="color:black" asp-controller="MainLogin" asp-action="Index">Login</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" style="color:black">Logout</a>
                                </li>

                                <li>
                                    <a class="dropdown-item" style="color:black" asp-controller="AddNewItems" asp-action="Index">Add New Items</a>
                                </li>

                                <li>
                                    <a class="dropdown-item" style="color:black" asp-controller="AddNewLogin" asp-action="Index">Add New Login</a>
                                   
                                </li>
                                <li>
                                    <a class="dropdown-item" style="color:black" data-bs-toggle="modal" data-bs-target="#CurrentLoginDetails">Update Login</a>

                                </li>
                            </ul>
                        </li>

                        

                    </ul>


                </div>

            </div>

        </nav>

        <!--Second NavBar-->
        <nav class="navbar box-shadow">

            <div class="container d-flex justify-content-center">

                <div class="">

                    <ul class="navbar-nav d-flex flex-row gap-3">

                        <li>
                            <a asp-controller="GentsItems" asp-action="Index" class="NavBarText nav-link">GENTS</a>
                        </li>

                        <li>
                            <a asp-controller="" asp-action="" class="NavBarText nav-link">WOMENS</a>
                        </li>

                        <li>
                            <a asp-controller="" asp-action="" class="NavBarText nav-link">KIDS</a>
                        </li>

                    </ul>

                </div>

            </div>


        </nav>

       
    </header>

    <!--Current Login details modal-->
    <div class="modal fade" tabindex="-1" id="CurrentLoginDetails">

        <div class="modal-dialog">

            <div class="modal-content">

                <div class="modal-header d-flex justify-content-center">
                    <div>
                        <h5 class="modal-title fw-bold">CURRENT LOGIN DETAILS</h5>
                    </div>

                    @* <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> *@
                </div>

                <form method="post" asp-controller="CheckingCurrentLogin" asp-action="Index">

                    <div class="modal-body">

                        <div class="container">

                            <!--Current username-->
                            <div class="row">

                                <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                                    <div>
                                        <label>Current Username</label>
                                    </div>

                                    <div>
                                        <input type="text" name="tbxCurrentUsername" class="form-control" placeholder="Current Username" />
                                    </div>
                                </div>
                            </div>

                            <!--Current password-->
                            <div class="row" style="padding-top:3%">

                                <div class="col-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                                    <div>
                                        <label>Current Password</label>
                                    </div>

                                    <div>
                                        <input type="password" name="tbxCurrentPassword" class="form-control" placeholder="Current Password" />
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">OK</button>
                    </div>

                </form>


            </div>

        </div>

    </div>


    <div class="container-fluid p-0 m-0">

        <main role="main">
            @RenderBody()
        </main>

    </div>

    <footer class="border-top footer text-muted">

        <div class="container">
            &copy; 2025 - VelvetVogue - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>